// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PP_Start","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"managers/DataManager","status":true,"description":"","parameters":{}},
{"name":"managers/ImageManager","status":true,"description":"","parameters":{}},
{"name":"managers/SpriteManager","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"scenes/Scene_Map","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"sprites/DirectionalSprite","status":true,"description":"","parameters":{}},
{"name":"sprites/PlayerSprite","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"entities/Player","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"other/DisableDefault","status":true,"description":"","parameters":{}},
{"name":"---","status":true,"description":"","parameters":{}},
{"name":"Playtest","status":true,"description":"","parameters":{}},
{"name":"PP_End","status":true,"description":"","parameters":{}}
];
